"""Alert manager module.

Manages alerts for monitoring events including selector drift,
scraping failures, and other issues.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from job_board_scraper.monitoring.selector_drift import DriftEvent

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Alert types and severity
# ---------------------------------------------------------------------------


class AlertSeverity(Enum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class AlertType(Enum):
    """Types of alerts."""

    SCRAPE_FAILURE = "scrape_failure"
    ZERO_JOBS = "zero_jobs"
    SELECTOR_DRIFT = "selector_drift"
    RATE_LIMIT = "rate_limit"
    ANTI_BOT = "anti_bot"
    PARSE_ERROR = "parse_error"
    SOURCE_UNAVAILABLE = "source_unavailable"


@dataclass
class Alert:
    """An alert generated by the monitoring system.

    Attributes:
        alert_type: Type of alert.
        severity: Severity level.
        source: Source/company slug that triggered the alert.
        message: Human-readable description.
        details: Additional context (dict).
        timestamp: When the alert was created.
        acknowledged: Whether the alert has been acknowledged.
    """

    alert_type: AlertType
    severity: AlertSeverity
    source: str
    message: str
    details: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    acknowledged: bool = False

    def to_dict(self) -> dict:
        """Convert alert to dictionary."""
        return {
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "source": self.source,
            "message": self.message,
            "details": self.details,
            "timestamp": self.timestamp.isoformat(),
            "acknowledged": self.acknowledged,
        }


# ---------------------------------------------------------------------------
# Alert handler types
# ---------------------------------------------------------------------------

AlertHandler = Callable[[Alert], None]
"""Type for alert handler callbacks."""


# ---------------------------------------------------------------------------
# Alert Manager
# ---------------------------------------------------------------------------


class AlertManager:
    """Manages alerts and notifications.

    The alert manager collects alerts from various sources and dispatches
    them to registered handlers (email, Slack, logging, etc.).

    Usage::

        manager = AlertManager()

        # Register handlers
        manager.register_handler(send_email_alert)
        manager.register_handler(log_alert)

        # Send alerts
        manager.alert(
            AlertType.SELECTOR_DRIFT,
            AlertSeverity.WARNING,
            "opswat",
            "Selector .job-card returned 0 matches",
        )

        # Acknowledge alerts
        manager.acknowledge(alert_id)
    """

    def __init__(self) -> None:
        """Initialize the alert manager."""
        self._handlers: list[AlertHandler] = []
        self._alerts: list[Alert] = []
        self._alert_id_counter = 0

    def register_handler(self, handler: AlertHandler) -> None:
        """Register an alert handler.

        Args:
            handler: Callable that takes an Alert and handles it.
        """
        self._handlers.append(handler)
        logger.debug("Registered alert handler: %s", handler.__name__)

    def unregister_handler(self, handler: AlertHandler) -> None:
        """Unregister an alert handler.

        Args:
            handler: Handler to remove.
        """
        if handler in self._handlers:
            self._handlers.remove(handler)
            logger.debug("Unregistered alert handler: %s", handler.__name__)

    def alert(
        self,
        alert_type: AlertType,
        severity: AlertSeverity,
        source: str,
        message: str,
        details: dict | None = None,
    ) -> Alert:
        """Send an alert to all registered handlers.

        Args:
            alert_type: Type of alert.
            severity: Severity level.
            source: Source/company slug.
            message: Human-readable description.
            details: Additional context.

        Returns:
            The created Alert object.
        """
        self._alert_id_counter += 1

        alert = Alert(
            alert_type=alert_type,
            severity=severity,
            source=source,
            message=message,
            details=details or {},
        )

        self._alerts.append(alert)

        # Dispatch to all handlers
        for handler in self._handlers:
            try:
                handler(alert)
            except Exception as e:
                logger.error(
                    "Alert handler %s raised exception: %s",
                    handler.__name__,
                    e,
                )

        logger.log(
            self._severity_to_log_level(severity),
            "Alert: [%s] %s - %s: %s",
            severity.value.upper(),
            alert_type.value,
            source,
            message,
        )

        return alert

    def handle_selector_drift(
        self,
        drift_event: DriftEvent,
        source: str,
    ) -> Alert:
        """Handle a selector drift event.

        Args:
            drift_event: The drift event from SelectorDriftDetector.
            source: Source/company slug.

        Returns:
            The created Alert object.
        """
        severity_map = {
            "warning": AlertSeverity.WARNING,
            "error": AlertSeverity.ERROR,
            "critical": AlertSeverity.CRITICAL,
        }

        severity = severity_map.get(drift_event.severity, AlertSeverity.WARNING)

        return self.alert(
            AlertType.SELECTOR_DRIFT,
            severity,
            source,
            f"Selector drift detected: {drift_event.message}",
            {
                "selector": drift_event.selector,
                "expected_min": drift_event.expected_min,
                "actual_count": drift_event.actual_count,
                "drift_severity": drift_event.severity,
            },
        )

    def handle_scrape_failure(
        self,
        source: str,
        error_message: str,
        is_partial: bool = False,
    ) -> Alert:
        """Handle a scraping failure.

        Args:
            source: Source/company slug.
            error_message: Error description.
            is_partial: Whether the scrape was partially successful.

        Returns:
            The created Alert object.
        """
        severity = AlertSeverity.WARNING if is_partial else AlertSeverity.ERROR

        return self.alert(
            AlertType.SCRAPE_FAILURE,
            severity,
            source,
            f"Scraping failed{' (partial)' if is_partial else ''}: {error_message}",
        )

    def handle_zero_jobs(
        self,
        source: str,
        job_count: int = 0,
    ) -> Alert:
        """Handle zero jobs returned.

        Args:
            source: Source/company slug.
            job_count: Number of jobs found (should be 0).

        Returns:
            The created Alert object.
        """
        return self.alert(
            AlertType.ZERO_JOBS,
            AlertSeverity.CRITICAL,
            source,
            f"Zero jobs returned from {source}!",
            {"job_count": job_count},
        )

    def handle_rate_limit(self, source: str) -> Alert:
        """Handle rate limit hit.

        Args:
            source: Source/company slug.

        Returns:
            The created Alert object.
        """
        return self.alert(
            AlertType.RATE_LIMIT,
            AlertSeverity.WARNING,
            source,
            f"Rate limit hit for {source}",
        )

    def handle_anti_bot(self, source: str) -> Alert:
        """Handle anti-bot detection.

        Args:
            source: Source/company slug.

        Returns:
            The created Alert object.
        """
        return self.alert(
            AlertType.ANTI_BOT,
            AlertSeverity.CRITICAL,
            source,
            f"Anti-bot protection detected for {source}",
        )

    def acknowledge(self, alert: Alert) -> None:
        """Acknowledge an alert.

        Args:
            alert: Alert to acknowledge.
        """
        alert.acknowledged = True
        logger.info("Alert acknowledged: %s", alert.message)

    def get_active_alerts(
        self,
        alert_type: AlertType | None = None,
        source: str | None = None,
        min_severity: AlertSeverity | None = None,
    ) -> list[Alert]:
        """Get active (unacknowledged) alerts.

        Args:
            alert_type: Filter by type.
            source: Filter by source.
            min_severity: Filter by minimum severity.

        Returns:
            List of matching alerts.
        """
        alerts = [a for a in self._alerts if not a.acknowledged]

        if alert_type:
            alerts = [a for a in alerts if a.alert_type == alert_type]

        if source:
            alerts = [a for a in alerts if a.source == source]

        if min_severity:
            alerts = [
                a
                for a in alerts
                if a.severity.value
                in [s.value for s in AlertSeverity if s.value >= min_severity.value]
            ]

        return alerts

    def clear_acknowledged(self) -> int:
        """Remove acknowledged alerts.

        Returns:
            Number of alerts removed.
        """
        before = len(self._alerts)
        self._alerts = [a for a in self._alerts if not a.acknowledged]
        return before - len(self._alerts)

    @staticmethod
    def _severity_to_log_level(severity: AlertSeverity) -> int:
        """Map alert severity to logging level."""
        return {
            AlertSeverity.INFO: logging.INFO,
            AlertSeverity.WARNING: logging.WARNING,
            AlertSeverity.ERROR: logging.ERROR,
            AlertSeverity.CRITICAL: logging.CRITICAL,
        }[severity]


# ---------------------------------------------------------------------------
# Default handlers
# ---------------------------------------------------------------------------


def log_alert_handler(alert: Alert) -> None:
    """Log alert to the application logger.

    This is a simple handler that logs alerts at the appropriate level.
    """
    logger.log(
        AlertManager._severity_to_log_level(alert.severity),
        "Alert [%s] %s: %s",
        alert.alert_type.value,
        alert.source,
        alert.message,
    )


# ---------------------------------------------------------------------------
# Global alert manager instance
# ---------------------------------------------------------------------------


_alert_manager: AlertManager | None = None


def get_alert_manager() -> AlertManager:
    """Get the global alert manager instance.

    Returns:
        The global AlertManager.
    """
    global _alert_manager
    if _alert_manager is None:
        _alert_manager = AlertManager()
        # Register default handlers
        _alert_manager.register_handler(log_alert_handler)
    return _alert_manager


def reset_alert_manager() -> None:
    """Reset the global alert manager (for testing)."""
    global _alert_manager
    _alert_manager = None
